#!/bin/sh

# Set these paths appropriately

BIN=/home/arielo/IdeaProjects/PaloTextAnalyzer/src/main/resources/treeTagger/bin
CMD=/home/arielo/IdeaProjects/PaloTextAnalyzer/src/main/resources/treeTagger/cmd
LIB=/home/arielo/IdeaProjects/PaloTextAnalyzer/src/main/resources/treeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
