#!/bin/sh

# Set these paths appropriately

BIN=/home/arielo/IdeaProjects/PaloTextAnalyzer/src/main/resources/treeTagger/bin
CMD=/home/arielo/IdeaProjects/PaloTextAnalyzer/src/main/resources/treeTagger/cmd
LIB=/home/arielo/IdeaProjects/PaloTextAnalyzer/src/main/resources/treeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
