#!/bin/sh

# Set these paths appropriately

BIN=/home/arielo/IdeaProjects/PaloTextAnalyzer/src/main/resources/treeTagger/bin
CMD=/home/arielo/IdeaProjects/PaloTextAnalyzer/src/main/resources/treeTagger/cmd
LIB=/home/arielo/IdeaProjects/PaloTextAnalyzer/src/main/resources/treeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
